//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QP_Management_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_Repository
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Info_Repository()
        {
            this.QP_Final_Pool = new HashSet<QP_Final_Pool>();
            this.QP_Version_Pool = new HashSet<QP_Version_Pool>();
        }
    
        public int DocInfoId { get; set; }
        public int Author { get; set; }
        public Nullable<int> Reviewer { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QP_Final_Pool> QP_Final_Pool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QP_Version_Pool> QP_Version_Pool { get; set; }
        public virtual Module Module { get; set; }
        public virtual User User1 { get; set; }
    }
}
