//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QP_Management_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QP_Final_Pool
    {
        public int DocInfoId { get; set; }
        public int QualityAnchor { get; set; }
        public System.DateTime AcceptanceTime { get; set; }
    
        public virtual Info_Repository Info_Repository { get; set; }
        public virtual User User { get; set; }
    }
}
