//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QP_Management_DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QP_Management_System_DBContext : DbContext
    {
        public QP_Management_System_DBContext()
            : base("name=QP_Management_System_DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Focus_Area> Focus_Area { get; set; }
        public virtual DbSet<Info_Repository> Info_Repository { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<QP_Final_Pool> QP_Final_Pool { get; set; }
        public virtual DbSet<QP_Version_Pool> QP_Version_Pool { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
