//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QP_Management_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QP_Version_Pool
    {
        public string DocId { get; set; }
        public string VersionId { get; set; }
        public byte[] Document { get; set; }
        public string DocumentName { get; set; }
        public Nullable<int> DocInfoId { get; set; }
    
        public virtual Info_Repository Info_Repository { get; set; }
    }
}
