//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QP_Management_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QPMasterPool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QPMasterPool()
        {
            this.QPVersions = new HashSet<QPVersion>();
        }
    
        public string QPDocId { get; set; }
        public byte[] Document { get; set; }
        public string DocumentName { get; set; }
        public string Author { get; set; }
        public string Reviewer { get; set; }
        public string QualityAnchor { get; set; }
        public string Status { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public System.DateTime CreationLog { get; set; }
        public Nullable<System.DateTime> UpdationLog { get; set; }
        public string Comments { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QPVersion> QPVersions { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
